# Generated by Django 4.1 on 2022-11-17 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(verbose_name='data publish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
